### ISSUE TITLE
[Bug] 无法正常获取农作物掉落物

### ISSUE THREAD

**Issue by Maplemoon233** [0XPYEX0/InvActions#1]
**描述**
右键马铃薯或者胡萝卜，服务器后台报错，并且游戏内并无掉落物

**复现步骤**
该Bug的复现步骤:
1:游戏内右击‘地上成长阶段为成熟的马铃薯/胡萝卜’
2. 马铃薯/土豆生长状态恢复为阶段一。但并掉落物
3. 查看服务器后台发现报错

**应该发生什么？**
如果Bug没有触发，鼠标右击已成熟的马铃薯/土豆，作物被采集，并自动种植，’掉落作物‘。

**截图**
服务器报错信息：![G07)3$ALU4R}Q2T)6GYSE@3](https://user-images.githubusercontent.com/110914918/209322398-7a0ff8d4-0a32-42ad-a3e2-f13a301aa778.png)
服务端已装插件列表：![L1X1`C~63P{HB8R3DZ8 I0J](https://user-images.githubusercontent.com/110914918/209322648-93aba2e5-186d-444c-a5eb-af01babd137a.png)

**版本信息(请参照例子，不要胡编乱造):**
 - 操作系统: Windows 11 22H2
 - Minecraft 1.19.3
 - 服务端核心 spigot-1.19.3.jar
 - InvActions-1.0.7
 - XPLib-1.0.4

**附加信息**
无

**Comment by 0XPYEX0** [comment]
最新版也这样？
我Paper 1.19.3 玩家用得可爽了 你确定吗

**Comment by Maplemoon233** [comment]
是的，最新版依旧如此，而且1.0.7还可以右键西瓜并收获，新版反而不行，我去试试paper端，有可能是spigot端的问题

**Comment by 0XPYEX0** [comment]
西瓜那个 要单独开配置文件 因为正常破坏西瓜南瓜是要耗费工具耐久度的 所以默认关闭
最新版的报错也截图附上来一张

**Comment by Maplemoon233** [comment]
报错：![%)}H3V@%MFYRP67PQ7(3(MH](https://user-images.githubusercontent.com/110914918/209326023-d7031cdf-c84c-48ad-bd52-711881babf49.png)
插件列表:![Y6GIS%SSF}J1@$CCMZWGH)4](https://user-images.githubusercontent.com/110914918/209326092-17700281-bc69-487f-b169-4eee62eac584.png)
我去试了paper-1.19.3-353.jar，可以正常使用

**Comment by 0XPYEX0** [comment]
更新1.1.1再试一次

**Comment by Maplemoon233** [comment]
1.1.1已可正常使用，感谢大佬
