### ISSUE TITLE
[Feature] 大佬，快捷能不能改成R  shift+R整理

### ISSUE THREAD

**Issue by hed516** [0XPYEX0/InvActions#2]
**你想要实现的功能是否与某个问题有关**
描述这个问题的有关信息. 如: 我不喜欢 [...] 功能

**描述实现方案**
描述一下如何实现你所提的功能，不一定要举代码，你也可以描述你所想的实现方式~

**描述备选方案**
如果上方的方案 无法实现，可以用什么方案实现这个功能

**附加信息**
如果有其它要补充的信息，请写在这里

**Comment by 0XPYEX0** [comment]
调整客户端切换副手按键

**Comment by 0XPYEX0** [comment]
调整客户端切换副手按键
